/**
 * Deterministic demo data used when X credentials aren't configured,
 * so the app is still beautifully browsable out-of-the-box.
 *
 * Everything here is clearly fictional and watermarked with an "[DEMO]"
 * author suffix so no one mistakes it for real reporting.
 */

import { uniqueBy } from "./utils";
import { ALL_SECTIONS_MAP, CORE_SECTIONS } from "./sections";
import type { PulsePost, PulseSummary, SectionFeed } from "./types";

interface SeedPost {
  author_handle: string;
  author_name: string;
  author_verified?: boolean;
  text: string;
  hoursAgo: number;
  url?: string | null;
  likes: number;
  replies: number;
  retweets: number;
  quotes: number;
  image?: string | null;
}

const PHOTOS = [
  "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=80",
  "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80",
  "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80",
  "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80",
  "https://images.unsplash.com/photo-1581090700227-1e37b190418e?w=1200&q=80",
  "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&q=80",
  "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80",
  "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=1200&q=80",
];

const SEEDS: Record<string, SeedPost[]> = {
  international: [
    {
      author_handle: "Reuters",
      author_name: "Reuters",
      author_verified: true,
      text: "BREAKING: European leaders agree on coordinated package of new measures following emergency summit in Brussels, diplomats say the agreement covers energy, trade and defense.",
      hoursAgo: 1.5,
      url: "https://www.reuters.com/world/europe/",
      likes: 12400,
      replies: 890,
      retweets: 5600,
      quotes: 420,
      image: PHOTOS[0],
    },
    {
      author_handle: "AP",
      author_name: "The Associated Press",
      author_verified: true,
      text: "Japan's parliament approves sweeping economic stimulus aimed at easing inflation pressure on households. The package is the largest since the pandemic.",
      hoursAgo: 3,
      url: "https://apnews.com/",
      likes: 5230,
      replies: 212,
      retweets: 1800,
      quotes: 180,
      image: PHOTOS[1],
    },
    {
      author_handle: "BBCWorld",
      author_name: "BBC News (World)",
      author_verified: true,
      text: "UN agencies warn of worsening food insecurity in the Horn of Africa as consecutive failed rainy seasons push millions into acute hunger, officials said.",
      hoursAgo: 5,
      url: "https://www.bbc.com/news/world",
      likes: 3100,
      replies: 190,
      retweets: 1500,
      quotes: 95,
      image: PHOTOS[2],
    },
    {
      author_handle: "AJEnglish",
      author_name: "Al Jazeera English",
      author_verified: true,
      text: "South Korea and Japan agree to expand intelligence sharing framework, signaling a thaw in relations as both countries face similar regional pressures.",
      hoursAgo: 7,
      url: null,
      likes: 2100,
      replies: 140,
      retweets: 980,
      quotes: 62,
    },
    {
      author_handle: "FT",
      author_name: "Financial Times",
      author_verified: true,
      text: "Global shipping rates rise for fifth consecutive week as carriers continue to reroute around key chokepoints, adding fresh pressure to consumer prices.",
      hoursAgo: 10,
      url: "https://www.ft.com/",
      likes: 1800,
      replies: 75,
      retweets: 620,
      quotes: 40,
      image: PHOTOS[3],
    },
    {
      author_handle: "guardian",
      author_name: "The Guardian",
      author_verified: true,
      text: "Record heatwave grips parts of South America with temperatures 10C above seasonal averages; authorities activate emergency plans for vulnerable populations.",
      hoursAgo: 12,
      url: "https://www.theguardian.com/world",
      likes: 2800,
      replies: 160,
      retweets: 900,
      quotes: 55,
      image: PHOTOS[4],
    },
    {
      author_handle: "WSJ",
      author_name: "The Wall Street Journal",
      author_verified: true,
      text: "Saudi Arabia and India announce expanded strategic partnership covering critical minerals, AI, and defense technology transfer, building on last year's joint declaration.",
      hoursAgo: 14,
      url: "https://www.wsj.com/",
      likes: 1600,
      replies: 90,
      retweets: 520,
      quotes: 33,
    },
    {
      author_handle: "NYTimes",
      author_name: "The New York Times",
      author_verified: true,
      text: "Analysis: Why this week's central bank signals matter for emerging markets — and the three countries most likely to move policy in response.",
      hoursAgo: 16,
      url: "https://www.nytimes.com/",
      likes: 2400,
      replies: 140,
      retweets: 700,
      quotes: 80,
    },
  ],
  national: [
    {
      author_handle: "AP",
      author_name: "The Associated Press",
      author_verified: true,
      text: "House advances bipartisan package on border security and judicial modernization; floor vote expected Thursday. Leaders in both chambers say the text is \"substantially complete.\"",
      hoursAgo: 2,
      url: "https://apnews.com/hub/politics",
      likes: 8200,
      replies: 1200,
      retweets: 2900,
      quotes: 310,
      image: PHOTOS[5],
    },
    {
      author_handle: "politico",
      author_name: "POLITICO",
      author_verified: true,
      text: "Scoop: White House reviewing new executive action on chip manufacturing incentives, sources familiar with the deliberations say. Announcement could come next week.",
      hoursAgo: 4,
      url: "https://www.politico.com/",
      likes: 4100,
      replies: 380,
      retweets: 1600,
      quotes: 140,
    },
    {
      author_handle: "washingtonpost",
      author_name: "The Washington Post",
      author_verified: true,
      text: "Federal Reserve officials signal patience on rate path as latest inflation data comes in slightly below expectations; markets rally on the news.",
      hoursAgo: 5,
      url: "https://www.washingtonpost.com/",
      likes: 3200,
      replies: 260,
      retweets: 1100,
      quotes: 95,
      image: PHOTOS[6],
    },
    {
      author_handle: "CBSNews",
      author_name: "CBS News",
      author_verified: true,
      text: "Severe storm system moving across the Plains has prompted tornado watches in three states. Residents are urged to follow local alerts.",
      hoursAgo: 7,
      url: "https://www.cbsnews.com/",
      likes: 1400,
      replies: 110,
      retweets: 680,
      quotes: 42,
    },
    {
      author_handle: "axios",
      author_name: "Axios",
      author_verified: true,
      text: "DOJ files civil complaint against major data broker over alleged mishandling of location data, seeking sweeping behavioral remedies.",
      hoursAgo: 9,
      url: "https://www.axios.com/",
      likes: 2600,
      replies: 180,
      retweets: 900,
      quotes: 58,
    },
    {
      author_handle: "nprpolitics",
      author_name: "NPR Politics",
      author_verified: true,
      text: "Governors from six states release joint letter urging Congress to act on housing supply, proposing new federal-state matching program.",
      hoursAgo: 12,
      url: null,
      likes: 1100,
      replies: 92,
      retweets: 420,
      quotes: 30,
    },
    {
      author_handle: "NBCNews",
      author_name: "NBC News",
      author_verified: true,
      text: "Exclusive: Internal documents show federal agencies are piloting new AI-assisted fraud detection tools, with early results showing notable accuracy gains.",
      hoursAgo: 15,
      url: "https://www.nbcnews.com/",
      likes: 1900,
      replies: 140,
      retweets: 610,
      quotes: 48,
      image: PHOTOS[7],
    },
    {
      author_handle: "WSJ",
      author_name: "The Wall Street Journal",
      author_verified: true,
      text: "Labor market remains resilient: job openings tick up modestly while layoffs stay near historic lows, according to latest federal data.",
      hoursAgo: 19,
      url: "https://www.wsj.com/",
      likes: 1700,
      replies: 88,
      retweets: 540,
      quotes: 35,
    },
  ],
  "foreign-policy": [
    {
      author_handle: "StateDept",
      author_name: "U.S. Department of State",
      author_verified: true,
      text: "Secretary Blinken concludes meetings with G7 counterparts; joint statement reaffirms coordinated response on sanctions enforcement and maritime security.",
      hoursAgo: 2,
      url: "https://www.state.gov/",
      likes: 3400,
      replies: 220,
      retweets: 900,
      quotes: 110,
    },
    {
      author_handle: "ForeignPolicy",
      author_name: "Foreign Policy",
      author_verified: true,
      text: "Analysis: The quiet rewiring of middle-power alliances — how Ankara, Abu Dhabi, and New Delhi are reshaping the global security architecture.",
      hoursAgo: 5,
      url: "https://foreignpolicy.com/",
      likes: 1800,
      replies: 130,
      retweets: 520,
      quotes: 60,
      image: PHOTOS[0],
    },
    {
      author_handle: "CFR_org",
      author_name: "Council on Foreign Relations",
      author_verified: true,
      text: "New report: Five scenarios for the next 24 months of Indo-Pacific security competition, and the one policymakers are still underestimating.",
      hoursAgo: 9,
      url: "https://www.cfr.org/",
      likes: 1100,
      replies: 80,
      retweets: 400,
      quotes: 32,
    },
    {
      author_handle: "ChathamHouse",
      author_name: "Chatham House",
      author_verified: true,
      text: "Our latest briefing examines the shifting dynamics of European defense spending and what it means for transatlantic burden-sharing.",
      hoursAgo: 14,
      url: null,
      likes: 620,
      replies: 40,
      retweets: 200,
      quotes: 15,
    },
    {
      author_handle: "DefenseOne",
      author_name: "Defense One",
      author_verified: true,
      text: "Pentagon issues new guidance streamlining foreign military sales; officials hope changes cut average approval time by a third.",
      hoursAgo: 18,
      url: "https://www.defenseone.com/",
      likes: 900,
      replies: 55,
      retweets: 310,
      quotes: 22,
    },
    {
      author_handle: "WarOnTheRocks",
      author_name: "War on the Rocks",
      author_verified: true,
      text: "New essay: The return of industrial policy in defense — lessons from Cold War-era mobilization for today's procurement backlog.",
      hoursAgo: 21,
      url: null,
      likes: 740,
      replies: 60,
      retweets: 230,
      quotes: 18,
      image: PHOTOS[2],
    },
  ],
  cybersecurity: [
    {
      author_handle: "briankrebs",
      author_name: "briankrebs",
      author_verified: true,
      text: "Major cloud provider discloses breach affecting several enterprise tenants; investigators say intrusion was discovered via proactive monitoring.",
      hoursAgo: 1,
      url: "https://krebsonsecurity.com/",
      likes: 5100,
      replies: 410,
      retweets: 2100,
      quotes: 240,
    },
    {
      author_handle: "TheHackersNews",
      author_name: "The Hacker News",
      author_verified: true,
      text: "New zero-day in widely deployed VPN appliance is being actively exploited in the wild. Vendors have released mitigations; patches expected within 48 hours.",
      hoursAgo: 3,
      url: "https://thehackernews.com/",
      likes: 2900,
      replies: 180,
      retweets: 1300,
      quotes: 110,
      image: PHOTOS[3],
    },
    {
      author_handle: "CISAgov",
      author_name: "CISA",
      author_verified: true,
      text: "CISA adds two new vulnerabilities to the Known Exploited Vulnerabilities Catalog. Federal agencies have 21 days to remediate.",
      hoursAgo: 6,
      url: "https://www.cisa.gov/",
      likes: 1300,
      replies: 60,
      retweets: 520,
      quotes: 30,
    },
    {
      author_handle: "BleepinComputer",
      author_name: "BleepingComputer",
      author_verified: true,
      text: "Ransomware group claims attack on regional healthcare provider; leak site posts alleged samples. Provider confirms \"cybersecurity incident\" and says care continues.",
      hoursAgo: 10,
      url: "https://www.bleepingcomputer.com/",
      likes: 1800,
      replies: 120,
      retweets: 720,
      quotes: 48,
    },
    {
      author_handle: "GoogleTAG",
      author_name: "Google Threat Analysis Group",
      author_verified: true,
      text: "We are tracking a new campaign from a state-aligned actor using a clever supply-chain technique; IOCs and mitigations in the post.",
      hoursAgo: 14,
      url: null,
      likes: 2200,
      replies: 95,
      retweets: 900,
      quotes: 60,
    },
    {
      author_handle: "Mandiant",
      author_name: "Mandiant",
      author_verified: true,
      text: "Our latest M-Trends highlights a notable shift in initial access vectors; social engineering remains dominant but cloud misconfig is rising fast.",
      hoursAgo: 18,
      url: "https://www.mandiant.com/",
      likes: 1000,
      replies: 40,
      retweets: 330,
      quotes: 22,
      image: PHOTOS[4],
    },
  ],
  "tech-news": [
    {
      author_handle: "verge",
      author_name: "The Verge",
      author_verified: true,
      text: "Major AI lab unveils new small model that outperforms larger predecessors on reasoning benchmarks while using a fraction of the compute.",
      hoursAgo: 2,
      url: "https://www.theverge.com/",
      likes: 6700,
      replies: 420,
      retweets: 2400,
      quotes: 310,
      image: PHOTOS[5],
    },
    {
      author_handle: "TechCrunch",
      author_name: "TechCrunch",
      author_verified: true,
      text: "Scoop: Robotics startup raises $220M to build warehouse automation hardware; deal values the company at roughly $1.6B post-money.",
      hoursAgo: 4,
      url: "https://techcrunch.com/",
      likes: 2100,
      replies: 140,
      retweets: 700,
      quotes: 55,
    },
    {
      author_handle: "WIRED",
      author_name: "WIRED",
      author_verified: true,
      text: "Inside the push to standardize open model evaluations — why benchmark drama is actually about trust.",
      hoursAgo: 7,
      url: "https://www.wired.com/",
      likes: 1600,
      replies: 110,
      retweets: 480,
      quotes: 42,
      image: PHOTOS[6],
    },
    {
      author_handle: "arstechnica",
      author_name: "Ars Technica",
      author_verified: true,
      text: "Deep dive: The hidden cost of \"infinite context\" — how long-context retrieval systems are actually performing in production.",
      hoursAgo: 12,
      url: "https://arstechnica.com/",
      likes: 1200,
      replies: 85,
      retweets: 380,
      quotes: 28,
    },
    {
      author_handle: "business",
      author_name: "Bloomberg",
      author_verified: true,
      text: "Apple, Google, and Meta are all quietly expanding their on-device AI teams — internal job data suggests the talent war is shifting again.",
      hoursAgo: 16,
      url: null,
      likes: 2400,
      replies: 160,
      retweets: 780,
      quotes: 60,
    },
    {
      author_handle: "CNBC",
      author_name: "CNBC",
      author_verified: true,
      text: "Chipmaker reports strong quarter driven by data center demand; guidance tops analyst expectations, shares up in after-hours trading.",
      hoursAgo: 20,
      url: "https://www.cnbc.com/",
      likes: 1800,
      replies: 95,
      retweets: 560,
      quotes: 40,
    },
  ],
  science: [
    {
      author_handle: "NASA",
      author_name: "NASA",
      author_verified: true,
      text: "Our latest Webb observations reveal surprisingly organized structures in a distant nebula — findings could reshape how we model early star formation.",
      hoursAgo: 3,
      url: "https://www.nasa.gov/",
      likes: 14000,
      replies: 620,
      retweets: 5800,
      quotes: 420,
      image: PHOTOS[7],
    },
    {
      author_handle: "sciam",
      author_name: "Scientific American",
      author_verified: true,
      text: "A new peer-reviewed study finds that a common blood test may detect early signs of a neurodegenerative disease years before symptoms appear.",
      hoursAgo: 6,
      url: "https://www.scientificamerican.com/",
      likes: 3200,
      replies: 210,
      retweets: 1100,
      quotes: 88,
    },
    {
      author_handle: "QuantaMagazine",
      author_name: "Quanta Magazine",
      author_verified: true,
      text: "Mathematicians announce progress on a decades-old conjecture. The elegant new proof builds on ideas borrowed from an unexpected field.",
      hoursAgo: 10,
      url: "https://www.quantamagazine.org/",
      likes: 1800,
      replies: 120,
      retweets: 560,
      quotes: 45,
      image: PHOTOS[0],
    },
    {
      author_handle: "NatureNews",
      author_name: "Nature News & Comment",
      author_verified: true,
      text: "Climate: New high-resolution ocean model captures eddy dynamics that had been invisible to earlier generations of simulations.",
      hoursAgo: 14,
      url: null,
      likes: 1300,
      replies: 70,
      retweets: 430,
      quotes: 26,
    },
    {
      author_handle: "NIH",
      author_name: "NIH",
      author_verified: true,
      text: "NIH-funded trial shows promising results for a next-generation gene therapy targeting a rare inherited blindness in children.",
      hoursAgo: 18,
      url: "https://www.nih.gov/",
      likes: 2100,
      replies: 95,
      retweets: 760,
      quotes: 52,
      image: PHOTOS[1],
    },
    {
      author_handle: "ESA",
      author_name: "European Space Agency",
      author_verified: true,
      text: "Our Mars rover team confirms successful sample cache — a key milestone for the planned joint sample-return mission.",
      hoursAgo: 22,
      url: null,
      likes: 1900,
      replies: 100,
      retweets: 620,
      quotes: 35,
    },
  ],
};

function stateSeedFor(name: string, hoursAgoBase: number): SeedPost[] {
  return [
    {
      author_handle: "local_news",
      author_name: `${name} Gazette`,
      author_verified: true,
      text: `${name} lawmakers advance budget package in committee; floor action expected later this week. Local officials describe negotiations as productive but ongoing.`,
      hoursAgo: hoursAgoBase,
      url: null,
      likes: 340,
      replies: 22,
      retweets: 110,
      quotes: 8,
      image: PHOTOS[(hoursAgoBase * 3) % PHOTOS.length],
    },
    {
      author_handle: "citywire",
      author_name: `${name} Wire`,
      author_verified: true,
      text: `Weather update: Active system moving across parts of ${name} could bring heavy rain and isolated strong storms overnight.`,
      hoursAgo: hoursAgoBase + 2,
      url: null,
      likes: 180,
      replies: 9,
      retweets: 60,
      quotes: 4,
    },
    {
      author_handle: "business_rep",
      author_name: `${name} Business Report`,
      author_verified: false,
      text: `Local employer announces expansion that could add hundreds of jobs over the next year; officials welcome the investment.`,
      hoursAgo: hoursAgoBase + 5,
      url: null,
      likes: 260,
      replies: 14,
      retweets: 80,
      quotes: 6,
    },
    {
      author_handle: "edu_update",
      author_name: `${name} Education Today`,
      author_verified: false,
      text: `State university system unveils new initiative aimed at workforce readiness, partnering with industry on credentialing pathways.`,
      hoursAgo: hoursAgoBase + 8,
      url: null,
      likes: 120,
      replies: 6,
      retweets: 40,
      quotes: 2,
      image: PHOTOS[(hoursAgoBase * 5 + 2) % PHOTOS.length],
    },
  ];
}

function seedToPost(
  sectionId: string,
  seed: SeedPost,
  idx: number,
  now: number,
): PulsePost {
  const created = new Date(now - seed.hoursAgo * 60 * 60 * 1000).toISOString();
  const id = `demo-${sectionId}-${idx}-${Math.floor(seed.hoursAgo * 60)}`;
  return {
    id,
    section_id: sectionId,
    author_handle: seed.author_handle,
    author_name: seed.author_name,
    author_verified: seed.author_verified,
    author_avatar: null,
    text: seed.text,
    created_at: created,
    url: seed.url ?? null,
    tweet_url: `https://x.com/${seed.author_handle}/status/${id}`,
    media: seed.image
      ? [
          {
            type: "photo",
            url: seed.image,
            preview_url: seed.image,
            width: 1200,
            height: 800,
            alt_text: null,
          },
        ]
      : [],
    metrics: {
      like_count: seed.likes,
      reply_count: seed.replies,
      retweet_count: seed.retweets,
      quote_count: seed.quotes,
    },
    fetched_at: new Date(now).toISOString(),
  };
}

export function buildDemoFeed(
  sectionId: string,
  timeframe: string,
  nowMs: number = Date.now(),
): SectionFeed {
  const section = ALL_SECTIONS_MAP[sectionId];
  let seeds: SeedPost[] = SEEDS[sectionId] ?? [];

  if (seeds.length === 0 && section?.group === "state") {
    seeds = stateSeedFor(section.name, 2);
  }

  const maxHours = timeframe === "6h" ? 6 : timeframe === "24h" ? 24 : 72;
  const filtered = seeds.filter((s) => s.hoursAgo <= maxHours);
  const posts = uniqueBy(
    filtered.map((s, i) => seedToPost(sectionId, s, i, nowMs)),
    (p) => p.id,
  );

  const summary: PulseSummary | null =
    posts.length === 0
      ? null
      : {
          section_id: sectionId,
          timeframe,
          overview: `[DEMO] Sample overview for ${section?.name ?? sectionId}. In production this is generated by Grok from live X posts. The highlights below are illustrative and use dated, fictional wording.`,
          themes: CORE_SECTIONS.some((s) => s.id === sectionId)
            ? ["policy", "markets", "security", "innovation"]
            : ["local government", "weather", "economy", "education"],
          takeaways: Object.fromEntries(
            posts.slice(0, 4).map((p) => [
              p.id,
              [
                "Key development worth following.",
                "Context: this relates to recent trends.",
                "Potential impact on stakeholders noted.",
              ],
            ]),
          ),
          generated_at: new Date(nowMs).toISOString(),
          input_hash: "demo",
        };

  return {
    section_id: sectionId,
    timeframe,
    posts,
    summary,
    updated_at: new Date(nowMs).toISOString(),
    cached: false,
    demo: true,
  };
}
